dtheta:
  custom: true
  values:
  - 1.0
energy_grid:
  custom: false
  n_points: 50
  scale: log
  vmax: 100000.0
  vmin: 1.0e-07
fps:
  custom: true
  values:
  - 10.0
r_obs:
  custom: true
  values:
  - 100000000000000.0
theta:
  custom: true
  values:
  - 1.0
  - 2.0
  - 3.0
  - 4.0
  - 5.0
  - 6.0
  - 7.0
  - 8.0
  - 9.0
tmax:
  custom: true
  values:
  - 40.0
tmin:
  custom: true
  values:
  - 0.0
